### ISSUE TITLE
"Waiting for Players" overlaps with certain in-game text

### ISSUE THREAD

**Issue by alcachofass** [alcachofass/devotion#48]
If a single player joins an empty server, the Waiting for Players message will render on screen. However, if the timer is enabled, it will overlap with other items. Ideally, this message should be moved to a screen location that won't cause any overlap issues.

**Comment by ceular** [comment]
change cg_timerposition back to 0 and it will be moved to the right corner, that is ratmod's default
https://github.com/alcachofass/devotion/blob/main/ratoa_gamecode/code/cgame/cg_main.c#LL509C24-L509C40

cg_timerscale is also important, i don't remember what was the default value but it was most likely 0
https://github.com/alcachofass/devotion/blob/main/ratoa_gamecode/code/cgame/cg_main.c#L713

alternatively, just grep cg_timerposition in cg_draw.c and adjust each value there

**Comment by alcachofass** [comment]
Thanks! I'll take a stab at it.
